Repository Moffinguer/decide-part-camaron-2, pull requests merged in 2023-12, with the labels that each got.

#42 Ci workflows
  .github/workflows/django.yml
  .github/workflows/prcmaster.yml
  .github/workflows/release.yml
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: integration

#44 Backup selection in restore
  .gitignore
  decide/decide/settings.py
  decide/store/templates/admin/store/vote/change_list.html
  decide/store/templates/confirm_delete.html
  decide/store/templates/delete_backups.html
  decide/store/templates/list_backups.html
  decide/store/tests.py
  decide/store/urls.py
  decide/store/views.py
Labels: enhancement

#61 Despliegue
  .github/workflows/deploy.yml
  decide/local_settings.deploy.py
  launch.sh
  requirements.txt
Labels: enhancement, integration

#59 Control Panel
  decide/decide/asgi.py
  decide/decide/settings.py
  decide/store/admin.py
  decide/store/consumers.py
  decide/store/templates/admin/store/change_form.html
  decide/store/templates/admin/store/vote/change_list.html
  decide/store/tests.py
  decide/store/views.py
  loadtest/locustfile.py
  requirements.txt
Labels: enhancement

#76 test(loadtest): added history voting loadtest
  decide/base/migrations/0001_initial.py
  decide/census/migrations/0001_initial.py
  decide/mixnet/migrations/0001_initial.py
  decide/postproc/migrations/0001_initial.py
  decide/store/migrations/0001_initial.py
  decide/voting/migrations/0001_initial.py
Labels: enhancement

#60 Postproc integration
  decide/authentication/test_selenium.py
  decide/base/migrations/0001_initial.py
  decide/booth/templates/booth/booth.html
  decide/booth/tests.py
  decide/booth/views.py
  decide/census/migrations/0001_initial.py
  decide/census/views.py
  decide/mixnet/migrations/0001_initial.py
  decide/mixnet/tests.py
  decide/pages.xlsx
  decide/postproc/migrations/0001_initial.py
  decide/postproc/tests.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_remove_vote_value.py
  decide/store/templates/admin/store/vote/change_list.html
  decide/store/templates/voteHistory.html
  decide/store/tests.py
  decide/store/urls.py
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/test_selenium_hierarchy.py
  decide/voting/test_selenium_preference.py
  decide/voting/test_selenium_yes_no_depende.py
  decide/voting/tests.py
  decide/voting/views.py
  docker/Dockerfile
  docker/createsuperuser.bash
  docker/docker-compose.yml
  loadtest/gen_census.py
  requirements.txt
Labels: integration
